name = "IOTables"
uuid = "4a7a88a2-08a2-4ed8-904f-89f2a6c4144f"
authors = ["Florian Forsthuber <florian.forsthuber@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
